# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd653072627fe4c94b2efe6c053bf2c86d228164a2a5d6ab88147cdc08ed7318ced59a024667314a0bf47c0459e6b23e85f343f659bbc16f8506a44bc035eda

test:
  secret_key_base: c47f1ea2f4881e34e0e45cba34abdf11dc985dd7e9a41f49103c3e3cd18819f52e1cd65f93987e067a54d64d932156915d03cc8e651d8a707b6ab3dba8aa705c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
