require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SkillsetsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Skillset. As you add validations to Skillset, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.attributes_for(:skillset) }

  let(:invalid_attributes) {{"id"=>"","skills"=>""}}

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SkillsetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all skillsets as @skillsets" do
      skillset = Skillset.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:skillsets)).to eq([skillset])
    end
  end

  describe "GET #show" do
    it "assigns the requested skillset as @skillset" do
      skillset = Skillset.create! valid_attributes
      get :show, params: {id: skillset.to_param}, session: valid_session
      expect(assigns(:skillset)).to eq(skillset)
      # expect(:get => "/skillsets/1").to route_to("skillsets#show", :id => "1")
    end
  end

  describe "GET #new" do
    it "assigns a new skillset as @skillset" do
      get :new, params: {}, session: valid_session
      expect(assigns(:skillset)).to be_a_new(Skillset)
    end
  end

  describe "GET #edit" do
    it "assigns the requested skillset as @skillset" do
      skillset = Skillset.create! valid_attributes
      get :edit, params: {id: skillset.to_param}, session: valid_session
      expect(assigns(:skillset)).to eq(skillset)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Skillset" do
        expect {
          post :create, params: {skillset: valid_attributes}, session: valid_session
        }.to change(Skillset, :count).by(1)
      end

      it "assigns a newly created skillset as @skillset" do
        post :create, params: {skillset: valid_attributes}, session: valid_session
        expect(assigns(:skillset)).to be_a(Skillset)
        expect(assigns(:skillset)).to be_persisted
      end

      it "redirects to the created skillset" do
        post :create, params: {skillset: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Skillset.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved skillset as @skillset" do
        post :create, params: {skillset: invalid_attributes}, session: valid_session
        expect(assigns(:skillset)).to be_a_new(Skillset)
      end

      it "re-renders the 'new' template" do
        post :create, params: {skillset: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip({"id"=>"1","skills"=>"phython"})
      }

      it "updates the requested skillset" do
        skillset = Skillset.create! valid_attributes
        put :update, params: {id: skillset.to_param, skillset: new_attributes}, session: valid_session
        skillset.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested skillset as @skillset" do
        skillset = Skillset.create! valid_attributes
        put :update, params: {id: skillset.to_param, skillset: valid_attributes}, session: valid_session
        expect(assigns(:skillset)).to eq(skillset)
      end

      it "redirects to the skillset" do
        skillset = Skillset.create! valid_attributes
        put :update, params: {id: skillset.to_param, skillset: valid_attributes}, session: valid_session
        expect(response).to redirect_to(skillset)
      end
    end

    context "with invalid params" do
      it "assigns the skillset as @skillset" do
        skillset = Skillset.create! valid_attributes
        put :update, params: {id: skillset.to_param, skillset: invalid_attributes}, session: valid_session
        expect(assigns(:skillset)).to eq(skillset)
      end

      it "re-renders the 'edit' template" do
        skillset = Skillset.create! valid_attributes
        put :update, params: {id: skillset.to_param, skillset: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested skillset" do
      skillset = Skillset.create! valid_attributes
      expect {
        delete :destroy, params: {id: skillset.to_param}, session: valid_session
      }.to change(Skillset, :count).by(-1)
    end

    it "redirects to the skillsets list" do
      skillset = Skillset.create! valid_attributes
      delete :destroy, params: {id: skillset.to_param}, session: valid_session
      expect(response).to redirect_to(skillsets_url)
    end
  end

end
